### ISSUE TITLE
Item properties are not displayed properly

### ISSUE THREAD

**Issue by sjaanus** [viktorgullmark/exilence#114]
![broken_flask](https://user-images.githubusercontent.com/964450/51086409-683a0980-174f-11e9-898a-95d96be74bbf.PNG)
![broken_require](https://user-images.githubusercontent.com/964450/51086410-683a0980-174f-11e9-9a65-6159625f0b95.PNG)

**Comment by petterannerwall** [comment]
Good catch, should be an easy fix with some regex or other string filtering method.

**Comment by sjaanus** [comment]
Working on it
