### ISSUE TITLE
Add reconnect-functionality to when pathofexile.com goes down

### ISSUE THREAD

**Issue by viktorgullmark** [viktorgullmark/exilence#118]
This can only be done for external sources (e.g pathofexile.com). 

Add X amount of retries, that fires every 30 seconds. 

Check if you were in a party (e.g partyservice.party !== undefined), and redirect to the main-screen for this party if true (current group).

**Comment by jnitis** [comment]
Ah, a self to-do note by a dev, nice. :-)

Yes, please.  I was going to suggest this.  Love the new server shutting down notice, but it would be worlds better to have the client auto-reconnect whenever there's a disconnection for any reason.  In fact, it'd be great if the client can hold a snapshot of the last known data and display that with a little "!" in the corner saying "last known data, trying to reconnect to server, server shutdown notice was (blah), server expected back up at 00:00."  Or, have the client cache the latest data locally before uploading and always read the data from there.

Thank you!

**Comment by viktorgullmark** [comment]
This could be done by implementing something similar to the reconnect-functionality for the SignalR-connection (see `party.service.ts`).

**Comment by viktorgullmark** [comment]
This should not be done before NgRx has been implemented. See https://github.com/viktorgullmark/exilence/issues/159

**Comment by viktorgullmark** [comment]
Started working on this: https://github.com/viktorgullmark/exilence/tree/features/offline-mode

**Comment by viktorgullmark** [comment]
Implemented in the latest release.
