### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Freakey1** [viktorgullmark/exilence#124]
Exilence auto-updated a few hours ago, and now I can't login.

I get this message: The sessionId or accountname is not valid, even tho I didn't change anything. Same accountname, same sessionID. I tried to relog into pathofexile.com to change the session ID, didn't work.

**Comment by jnitis** [comment]
0.9.11 resolved this issue for me, thank you.

**Comment by Freakey1** [comment]
Solved!

**Comment by viktorgullmark** [comment]
Glad to hear, closing this.
