### ISSUE TITLE
not validating session id still in 0.9.11

### ISSUE THREAD

**Issue by Adiwcs** [viktorgullmark/exilence#125]
as the title says

**Comment by Adiwcs** [comment]
I have 0 standard character, this is my first league, If u need any specific screenshots, tell me, i will assist.

**Comment by viktorgullmark** [comment]
Great that it works!

Yea, we'll fix this / add a text for it. Closing this. :)

**Comment by joeflack4** [comment]
+1 to the suggestion. just had the same issue.

**Comment by viktorgullmark** [comment]
This has been fixed. What exactly is your issue @joeflack4 ? We look in all leagues where you have characters now. Attach print screens if you're experiencing an issue with this still, and mention what version it is.

**Comment by joeflack4** [comment]
I can happily report that it is working now. It was previously stuck on validation, just continuously playing the "progress" animation.

I'm not sure what's up with my Windows PC, but it seems to me like certain JS-based desktop apps (perhaps all Electron based; I am not sure) have intermittent difficulty connecting to the internet. If I ever find out more, I'll update you.
