### ISSUE TITLE
Remove the limit on how may tabs we can select.

### ISSUE THREAD

**Issue by ZeroCool940711** [viktorgullmark/exilence#176]
Right now there is a limit of 40 tabs max that you can select for exilence to include, some of us have more than 300+ tabs, is there any way this value could be increased?

**Comment by viktorgullmark** [comment]
We might consider adding a setting for this. However, there will be side-effects of this since GGG rate-limits their API and only accepts a certain amount of requests per minute. One stashtab is one request.

**Comment by viktorgullmark** [comment]
Closing this for now, but will talk internally if we can add an option for increasing the stashtab-max.
