### ISSUE TITLE
NetWorth history: Differentiate Price updates and looting/stash changes

### ISSUE THREAD

**Issue by arberg** [viktorgullmark/exilence#190]
Awesome tool, and beautiful too. Congrats on creating such awesomeness :)

I noticed my net-worth changed more than I expected after trading currency. I suspect this could be because new priced were received from poe.ninja on my items. Its quite relevant for me to see the value of my strategy for farming and trading, and for this I need a period where prices of all my items are fixed. 

One option would be pausing price updates, or only update prices when app starts, though that seems to rarely. Also I guess a setting would be necessary as users have different needs.

Actually I don't know how often it updates prices, I just saw the fluctuation.

**Comment by viktorgullmark** [comment]
Thanks for your comment!

This is a really good suggestion and I've been thinking of this myself too. We'll see how we'll implement it, most likely a setting under "Net worth". It updates approx every 10 minutes, FYI.

Closing and opening issue for implementing this. See https://github.com/viktorgullmark/exilence/issues/191
