### ISSUE TITLE
Add an option for turning off retrieval of prices

### ISSUE THREAD

**Issue by viktorgullmark** [viktorgullmark/exilence#191]
Some users prefer to have a fixed price when playing, to see more exact changes of their net worth. (https://github.com/viktorgullmark/exilence/issues/190)

**Comment by viktorgullmark** [comment]
https://github.com/viktorgullmark/exilence/commit/e3f509010855616585f3a84475722193bf6022d4

**Comment by arberg** [comment]
Oohh I look forward to trying this out. I've been busy hence my unresponsiveness.
