### ISSUE TITLE
None of the hyperlinks in the application work.

### ISSUE THREAD

**Issue by gotex007** [viktorgullmark/exilence#198]
The Patreon, Discord, and ["this link" (screenshot)](https://i.imgur.com/ZZ77xta.png) don't work when clicked. Neither does ["go to profile"](https://i.imgur.com/ZG7qn4b.png).

**Comment by viktorgullmark** [comment]
What windows-version are you running? Can you try starting the application as administrator? This has never been an issue before.

**Comment by gotex007** [comment]
They appear to work now. They didn't work before. I'm not sure why.

**Comment by viktorgullmark** [comment]
Glad it works, let us know if you can replicate it in the future and provide any steps doing so.
