### ISSUE TITLE
Tracker mispricing item

### ISSUE THREAD

**Issue by onyilam10** [viktorgullmark/exilence#204]
As you can see it counts plateau as 50 chaos item while its actually not... 
![image](https://user-images.githubusercontent.com/25664557/53979939-5cdfda80-410f-11e9-9701-15ea4ff30a92.png)

**Comment by viktorgullmark** [comment]
This is an issue from https://poe.ninja. We're in contact with him and trying to resolve this issue. We have logging in place that tracks these "hickups". Closing this as we've added logging for this in a previous issue, as it is currently being worked on.
