### ISSUE TITLE
Bug: Only shows my chaos orbs, when disabling setting 'Automatic price-updates'

### ISSUE THREAD

**Issue by arberg** [viktorgullmark/exilence#207]
v0.9.28 beta

If I disable 'Automatic price-updates', then after the next update of my items (the red line above currency) then it only shows my chaos orbs, and compute my net-worth from that. If I disable setting and restart exilence, it reloads all after a short while. 

It must be price-update that's wrong and not gear update, because my currency-quantities in exilence is wrong / out-dated.

**Comment by viktorgullmark** [comment]
Can you provide print-screens of this? I can't seem to replicate it locally.

**Comment by viktorgullmark** [comment]
Nevermind, was able to fix this. https://github.com/viktorgullmark/exilence/commit/93ac5a4e3813c221b2ac84f7c2f09a595102231a

Will be released with our next update.
