### ISSUE TITLE
Interesting valuation of scrolls

### ISSUE THREAD

**Issue by aeons** [viktorgullmark/exilence#209]
I'm not sure this is an issue with exilence or with wherever the pricing is pulled from, but this seems like sketchy math at the least.

![image](https://user-images.githubusercontent.com/1432894/54086518-6dc86000-434a-11e9-8886-3194d5f734b3.png)

**Comment by viktorgullmark** [comment]
The calculated price represents the value from poe.ninja, while the others are from poe.watch. We need to put a text that explains this, but theres nothing wrong with the prices. 

We might add an option to choose price-source in the future.
