### ISSUE TITLE
Characters are duplicated in the group

### ISSUE THREAD

**Issue by viktorgullmark** [viktorgullmark/exilence#215]
https://gyazo.com/f48242fef83a60aacf084941cb79339d

This was sent to me on reddit. I'm not sure how or when it occurs.

**Comment by petterannerwall** [comment]
Probably has something to do with us only comparing the connectionId for existing players when joining a party.

**Comment by viktorgullmark** [comment]
Talked some more to Jkurs. Apparently his friend has very bad internetconnection, which is most likely causing reconnects to the group. Something seems off with the "oldPlayer" variable in our backend.

**Comment by viktorgullmark** [comment]
Fixed with https://github.com/viktorgullmark/exilence/commit/d9cc531453d1b77f2e860a58494af48843735fea and will be live with 0.9.32. Closing.
