### ISSUE TITLE
Improve scaling of the graph to reflect smaller fluctuations better

### ISSUE THREAD

**Issue by dedimistrz** [viktorgullmark/exilence#221]
Its just a small suggestion but can we have better network graph scale ?

i mean networth in upper graph is like always just a line for me. Can we have some top scale or let it start from 0 if we want ?

like even if i gain/lost 10 ex its just so small on graph i cant see diffrence.
![obraz](https://user-images.githubusercontent.com/1877002/58208986-557ba680-7ce6-11e9-8804-c18c90524349.png)

**Comment by Krzysiu** [comment]
I've got some problems, so I can't test it, but try:
`Settings -> Net worth -> Net worth history for...` <sup>[on the bottom of tab; scroll down]</sup>

**Comment by viktorgullmark** [comment]
Try what Krzysiu suggested and let us know how it works. We're pretty limited in how the graph behaves currently, but some tweaking can always be done. 

I'll leave this issue open and see what we can do about this in the future, in the meantime, let us know how the above works out for you.

**Comment by dedimistrz** [comment]
it does help me a little but kinde not enough as i would like to work.
Can we have an option to start graph from bottom left so we can clearly see diffrences ? not like line started from middle of the space

**Comment by dedimistrz** [comment]
![obraz](https://user-images.githubusercontent.com/1877002/59962611-0e045800-94e8-11e9-8c70-22d3326f22c4.png)
sorry issue to close.
it works extemly good now with that options.
well done guys.

**Comment by viktorgullmark** [comment]
Glad to hear! :) Closing this.
