### ISSUE TITLE
Updates work in backend, frontend frozen

### ISSUE THREAD

**Issue by Krzysiu** [viktorgullmark/exilence#224]
Since a few hours nothing updates - graph stays the same, history as well. Yet when I run the Exilence again, past data is shown, including areas etc. - like everything's recording, but just not showing. I've tried logging in and out, different settings and at last deleting %APPDATA%/Exilence directory with settings and starting from scratch. It didn't help. Any clues? Anything more I could try to reset? Some logs/dumps to show?

**Comment by petterannerwall** [comment]
@Krzysiu I did a update of the backends yesterday, will have to check the backend logs and see if i can find anything.

**Comment by petterannerwall** [comment]
Yea confirmed that i mistakenly left a debug row in when i published. So if you don't have any gloves names "Pandemonium Palm" in your inventory or equipped the update is crashing.

**Comment by petterannerwall** [comment]
New backends are released. Please let me know if it doesn't work.
