### ISSUE TITLE
[Suggestion] Change Keybind Trigger-key selection to keystroke capture.

### ISSUE THREAD

**Issue by Megaddd** [viktorgullmark/exilence#23]
Instead of scrolling through a massive dialog window, display 'press key' and capture the next keystroke as the trigger-key instead, set as 'none' by pressing ESC.

**Comment by viktorgullmark** [comment]
Closing this as of now. Not something we currently want to spend resources on, would require us to exclude too many combinations too, to not overlap with native functionality.
