### ISSUE TITLE
linux/macos

### ISSUE THREAD

**Issue by ccomly** [viktorgullmark/exilence#230]
any possibility to move over to some inclusive dependencys, linux and mac would be cool!

**Comment by viktorgullmark** [comment]
We're working on a rework of Exilence, will see what we can do on this part!

**Comment by Saturate** [comment]
This seems like a good idea, with the official support for MacOS coming soon!

**Comment by SirKhaoz** [comment]
+1 seeing as the MacOS support is releasing in a few weeks!
