### ISSUE TITLE
Exilence not updating on its own (only on restart)

### ISSUE THREAD

**Issue by projectsix84** [viktorgullmark/exilence#231]
Been using the program for a while now without issue, but tonight I'm having a problem where my net worth and areas entered are not updating on their own. I've left it running for a while, ran a few maps, etc. It does update everything once I close and restart Exilence, though.

Any ideas?  Thanks for the great app!

**Comment by viktorgullmark** [comment]
This means either Path of Exile can't access your Client.txt file, is not writing to it, or that the path is wrong. Check the contents of the file to make sure it's the right one.
