### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by CowBlaster** [viktorgullmark/exilence#240]
I get the error "The session id or account name is not valid" when I try to validate my sessionId

Though I know my account name and session id are correct, I tried reinstalling Exilence, restarting my PC, relogging on pathofexile.com, nothing seems to work.

**Comment by mtutin** [comment]
Same for me

**Comment by Sunflip** [comment]
Same for me, stopped updating for me just like that around 8-9 hours ago

**Comment by nkofferman** [comment]
same here, other apps can use the same sessionid successfully.

**Comment by AngryRoleplayer** [comment]
same

**Comment by hyorran** [comment]
same

**Comment by projectsix84** [comment]
Same issue. Tried logging out and logging back in of the official poe site. Tried logging in normally and also through steam. Nothing seems to work.. just says it's the sessionid isn't valid.

**Comment by Elementariado** [comment]
the same happening's Here.  tried various times of sessions whenever it was through, my original email or it was assigned through Steam. When I just don't put ANY sessionid - the login works in Exilence. However when I'm putting the correct SessionId with login - it still continues to say "The session id or account name is not valid"

**Comment by emrold** [comment]
Same. Tried clearing cookies and renewing session id
