### ISSUE TITLE
Can't capture Exilence in OBS Studio anymore

### ISSUE THREAD

**Issue by AngryRoleplayer** [viktorgullmark/exilence#241]
I had windows 7 for a while and previous version of Exilence as well (the one before the cookie update).
I used OBS window capture feature to capture Net Worth overlay to show live on stream. 
![image](https://user-images.githubusercontent.com/22470478/62936283-13886b00-bdd2-11e9-8835-aba93e84b3ca.png)
Recently i upgraded to win 10 as well as new Exilence and no matter what i do i only get black sceen now when i try to capture Exilence. 
Maybe Exilence changed specific window setting, maybe it uses hardware acceleration of some kind? 
It does capture the cursor but the window stays black

**Comment by viktorgullmark** [comment]
We didn't change anything related to the popout iirc. We'll look into solutions to be able to capture it correctly in Windows 10 for E Next.

Thanks for your report.
