### ISSUE TITLE
Unique Collection tab not being tracked

### ISSUE THREAD

**Issue by Overwatching** [viktorgullmark/exilence#246]
I picked up a few high value uniques and put them in the Unique Collection tab.

The items have a high confidence on poe.ninja so they should be tracked properly. But after an hour they still aren't showing up.

**Comment by Overwatching** [comment]
Putting the items in a different tab makes them show up fine. So it's definitely not the items themselves.

**Comment by viktorgullmark** [comment]
This is a known issue which is not solvable on our end, we rely on GGG for this. This is because the tab is not supported in their API (since it's basically a "tab-in-tab"). Closing.

**Comment by Overwatching** [comment]
Ahh. I looked around and didn't see anything indicating it. I hadn't thought to dig into the API to see if the tab was even supported. I assumed it was since the other "collections" tabs seem to work fine (Currency/Essences/Divination/Maps/etc)

Perhaps put a note in the main readme?
