### ISSUE TITLE
Could not connect to Exilence server

### ISSUE THREAD

**Issue by DemiunN** [viktorgullmark/exilence#249]
My Exilence keeps disconecting. It doesnt matter if I link it to my profile or try to join group, I still cant connect.
Its like this for 4 days, tried to log in with new ID, reinstall app, nothing is working.

"This can be caused for multiple reasons. But we listed the most probable ones below:
Exilence is down for maintenance (should be up within 30 minutes)
We experienced some connectivity issues between our server and your client
Relaunch Exilence to reconnect, and install the update if prompted."

**Comment by viktorgullmark** [comment]
Read the popup you're getting when you login, or join our Discord.
