### ISSUE TITLE
[Bug] Text display issue for abyss jewel

### ISSUE THREAD

**Issue by Aramerith** [viktorgullmark/exilence#25]
Minor one, but found out just fetching my character in the app.

![Bug screenshot](https://i.imgur.com/V9dqHvM.png)

**Comment by MonoLizard** [comment]
Already fixed in https://github.com/viktorgullmark/exilence/commit/eefd67231ef589a84e80a87d9d7810db796e2334#diff-7ee8575540dfb0dd35fcf1ce3fb6025f.

**Comment by viktorgullmark** [comment]
Good find, thanks @MonoLizard. Closing.
