### ISSUE TITLE
[Enhancement] 1 click restart when an update is available

### ISSUE THREAD

**Issue by aggixx** [viktorgullmark/exilence#35]
![image](https://user-images.githubusercontent.com/510805/49405864-742ab880-f719-11e8-9735-5a9c3d0a91a8.png)

Would be a nice, hopefully simple, QoL feature to be able to click on the pink banner to instantly restart the app. Maybe have a confirmation prompt, or better imo, click & hold for like 1s, to avoid accidental restarts.

**Comment by viktorgullmark** [comment]
![image](https://user-images.githubusercontent.com/11405940/49430121-7f79f480-f7aa-11e8-8c9a-4edcb97abdd8.png)

Added in 0.8.3, will be released in 1-2 days.

**Comment by viktorgullmark** [comment]
Closing this, the change is now live. However, it can be improved and probably will be, with a confirmation prompt or delay as you suggested.
