### ISSUE TITLE
[Suggestion] Manually refresh character tab

### ISSUE THREAD

**Issue by MercerK** [viktorgullmark/exilence#40]
I'm playing with a newer player, who also has this program installed. It would be great to be able to click on a 'refresh' button within the character tab to request the latest information for that character (equipped/inventory) while they are in town. 

This can allow me to observe and continually help them improve.

**Comment by viktorgullmark** [comment]
We fetch the character-data as often as GGG updates it on the website, which currently is on zone-change. We don't read the items from the game directly, so currently this is sadly not a possibility.
