### ISSUE TITLE
[Suggestion] Show 'Disconnect' & ability to reconnect, versus relaunching. 

### ISSUE THREAD

**Issue by MercerK** [viktorgullmark/exilence#42]
When using this in a party, every so often, it disconnects and goes to the "You need to relaunch Exilence and here are all the possible reasons", losing **all** capability until you relaunch. 

It would be much preferred that the client "disconnects" from live feeds, and attempts to reconnect automatically on its own, versus having the user to "relaunch exilence" every so often to restore connectivity. (On another note, it tends to open up on the main screen, versus on the screen it was previously on),

Even when the client is disconnected, it is still beneficial to see the data (even though it might be outdated).

**Comment by viktorgullmark** [comment]
https://github.com/viktorgullmark/exilence/issues/118
