### ISSUE TITLE
Massive RAM Usage (possible leak)

### ISSUE THREAD

**Issue by lmikulla** [viktorgullmark/exilence#44]
![image](https://user-images.githubusercontent.com/5196795/49810155-e0806a00-fd60-11e8-9d75-08bce905f999.png)

The RAM Usage of exilence goes massive after a long session. In the Screenshot it has been running for about 8 hours, in a 2 man party. When freshly started it hovers around 300MB which is really high but acceptable, but it should not balloon up to 2GB i think.

**Comment by viktorgullmark** [comment]
Thanks for the information. Looked at this really briefly and it might be related to how we dispose of (or rather not dispose of) some asynchronous lists. Will investigate further later tonight after work and see what we can do about it.

**Comment by viktorgullmark** [comment]
Closing this. Fixed in 0.8.9. It's not released yet but you can grab the prebuild at https://ufile.io/pqk2t
