### ISSUE TITLE
Support for gain per map/area

### ISSUE THREAD

**Issue by viktorgullmark** [viktorgullmark/exilence#51]
How it should work:

1. Take a snapshot of the inventory when you enter an area that isn't a hideout or town.

2. Based on instance-server and last zone, decide whether the map/area is complete or not, and take another snapshot of the inventory.

3. Compare these two snapshots and calculate the difference in items (see currency-summary gain for reference).

4. Add a column to the areas-tab that displays the gain for each map/area.

**Comment by viktorgullmark** [comment]
Added in the upcoming release, closing.

**Comment by Deser0** [comment]
This feature is not working for me. It shows always -
no gain value, what am i doing wrong?

**Comment by Davst** [comment]
Can confirm that this isn't working. would love a fix

**Comment by viktorgullmark** [comment]
We can confirm it's not working. We'll look into a fix when we have time, see related issues.
