### ISSUE TITLE
Add proper state management

### ISSUE THREAD

**Issue by petterannerwall** [viktorgullmark/exilence#56]
This is a big one, requires rewriting logic in almost all components but it needs to be done sometime.

Useful links: https://github.com/ngxs/store

**Comment by petterannerwall** [comment]
This is a big one, requires rewriting logic in almost all components but it needs to be done sometime.

**Comment by petterannerwall** [comment]
This is a big one, requires rewriting logic in almost all components but it needs to be done sometime.

**Comment by viktorgullmark** [comment]
Has been added, but is not currently used for previous implementations. Will be an on-going project.
