### ISSUE TITLE
Change the url that is used to validate SessionId

### ISSUE THREAD

**Issue by viktorgullmark** [viktorgullmark/exilence#62]
Right now, we validate the following way:

A request is sent to the website, that tries to select the first stash-tab in Standard-league. This will not work on a new account, since GGG does not index tabs in Standard until you've manually touched them (e.g logging in, opening the stash, and then logging out).

We should change this url to be a more generic one, that everyone will be able to use.

**Comment by petterannerwall** [comment]
Did a quick look but don't know if there are any good one to use... See here: https://app.swaggerhub.com/apis/Chuanhsing/poe/1.0.0

**Comment by valseria** [comment]
Is it to verify that said account has characters and/or stash tabs?

**Comment by viktorgullmark** [comment]
No, it's to verify that the actual sessionId is valid.
