### ISSUE TITLE
Show informative text if the stashtype is "MapTab"

### ISSUE THREAD

**Issue by viktorgullmark** [viktorgullmark/exilence#70]
Since GGG does not provide maptabs in their API, we should provide an explanation for this in the client. 

Suggestion: Grey out the tab in the stash-selection, and show a text upon hovering on the tab.

**Comment by sjaanus** [comment]
Is this still relevant?

**Comment by viktorgullmark** [comment]
@sjaanus Nope, thanks for pointing it out. This one is obsolete since we've added the maptab now. Closing.
