### ISSUE TITLE
Change compression algoritm from gzip to lz4

### ISSUE THREAD

**Issue by petterannerwall** [viktorgullmark/exilence#72]
To improve performance and eliminate a possible bottleneck we should switch to a faster compression algoritm when sending and storing data. The fastest one around in lz4 so we should use that. Reference: https://lz4.github.io/lz4/

**Comment by petterannerwall** [comment]
Cool, Any help is very appriciated! This issue should be pretty straight forward, At start we could just have some new methods in the CompressionHelper class and compress the data that get's saved in Redis. If you want to go further the next step is to compress the data that gets sent to the client aswell. That would require a node library to decompress the data. On the client the compression resides in electron.service.ts 

I was thinking we could at start just use the pickler option in the C# library you linked.

When you think you're ready just make a PR and we'll take a look at it!

**Comment by valseria** [comment]
New branch "LZ4", studying the manual atm. 
Would you also like hashing for data corruption detection too? (https://github.com/Cyan4973/xxHash)

**Comment by viktorgullmark** [comment]
@valseria Cool! Can you link me the branch? It doesn't appear on your fork, not sure which account you're using. 

Can you explain what would be the benefit for us to include hashing? I don't see a reason right now.

**Comment by valseria** [comment]
It's to make sure that the server isn't accidentally serving corrupt data and it gives the client quick way to verify that the data it is getting isn't corrupted. Optional atm but really it would be as easy as adding the xxhash library and adding a another parameter to a LZ4 Stream compression/decompression call.
The branch was only local on my PC, I hadn't quite pushed the branch, its still local on my pc, I've only imported the libraries, I'll push the branch later tonight.

**Comment by valseria** [comment]
Hey I figured I would give you guys an update.
xxHash is a requirement for the K4os LZ4 stream encoding library I imported. 
I've also found that we could use [LZ4Pickler](https://github.com/MiloszKrajewski/K4os.Compression.LZ4#Pickler) but it would just be faster and more efficient to instead use `LZ4Stream.Encode(input) `. 
![pickle](https://user-images.githubusercontent.com/45887085/50217859-e1a42f00-033e-11e9-832d-96454aeeaf59.png)

**Comment by valseria** [comment]
`Please note that stream decompression is (at least I hope it is) fully compatible with original specification. Well, it does not handle predefined dictionaries but lz4.exe does not either. All the other features which are not implemented yet (ContentLength, ContentChecksum, BlockChecksum) are just gracefully ignored but does not cause decompression to fail.`[from K4os page](
https://github.com/MiloszKrajewski/K4os.Compression.LZ4#stream-decompression)

We can use this at least for now.
In the future, we could potentially further optimize traffic by using static dictionaries too.

**Comment by viktorgullmark** [comment]
Closing this for now. Been in progress for a long time and we've reconsidered; keeping gzip for now.
