### ISSUE TITLE
Add timings to track performance of backend

### ISSUE THREAD

**Issue by petterannerwall** [viktorgullmark/exilence#76]
Add as save timing of most used endpoints in signalr along with compression/decompression. We need to know more about what parts of the backend that takes performance.

**Comment by valseria** [comment]
We can accomplish this by instead running a profiler such as [dotTrace by jetbrains](https://www.jetbrains.com/profiler/). 
I have this, and can totally do the profiling too, and I'll be sure to send the data on that.

**Comment by valseria** [comment]
[jetbrains docs: .NET Core application profiling](https://www.jetbrains.com/help/profiler/Profile_.NET_Core_Application.html)

[Here's the API for dotTrace](https://www.jetbrains.com/help/profiler/Profiling_Guidelines__Advanced_Profiling_Using_dotTrace_API.html)

This is what we could use that global debug flag for.

**Comment by viktorgullmark** [comment]
We've added this with Application Insights, currently disabled though but can be activated as needed. Closing this, will look into dotTrace in the future too.
