### ISSUE TITLE
Total account wealth fluctuates wildly if stash is full of items priced in alch.

### ISSUE THREAD

**Issue by Megaddd** [viktorgullmark/exilence#8]
Because the conversion of alchemy to chaos in poe.ninja fluctuates by small decimal points in real time, if you have many (1000's) items priced in alch in the stash, your Current net chaos worth moves up and down by 10's of chaos in real time, even if you've been doing nothing but gaining currency the entire time: https://gfycat.com/GiddyGaseousCranefly

**Comment by Megaddd** [comment]
Still moving up/down randomly a bit https://i.imgur.com/jjNQBzq.png

**Comment by viktorgullmark** [comment]
Closing this. We've added support to choose which items to include (by default anything above chaos, but less can be chosen too).
