### ISSUE TITLE
Add a quick-swap dropdown for characters

### ISSUE THREAD

**Issue by viktorgullmark** [viktorgullmark/exilence#86]
Add the ability to "quick-swap" characters, without logging out and going through the entire process again. Should be a simple dropdown in the top-right above the group-name form. List characters of the current league and swap instantly when the dropdown changes, then send a updateplayer-event.

**Comment by viktorgullmark** [comment]
Discussed this internally. It should be a complete "profile"-function instead, that stores login-settings as different profiles.

**Comment by piposanchez** [comment]
Any news on this? I have my trickster with most of my farming sessions, but when I switched to my slayer and equipped the starforge i looted, it showed as a huge drop in networth. How can I do it so my slayer gets added (and his gear counted) so i don't get these currency spikes?
Thanks in advance

**Comment by viktorgullmark** [comment]
There's no news on this right now. We're looking into a more long-term solution for this that we'll hopefully announce shortly.

Closing for now.
