### ISSUE TITLE
Scarabs are not valued if stacked in fragment tab

### ISSUE THREAD

**Issue by SirFist** [viktorgullmark/exilence#94]
As titled. Haven't actually tried moving them but they are certainly not in the list of valuables while they are in an indexed fragment tab.

**Comment by viktorgullmark** [comment]
Thanks for the info, will have to check this out later, haven't actually tested myself since I don't own any scarabs.

**Comment by SirFist** [comment]
0.9.1 beta, it pulls other things like actual breahc splinters from the same tab without issue.

**Comment by viktorgullmark** [comment]
Thanks, will investigate tonight after work!
